name: flutter_shopping_cart
description: Flutter example of shopping app using Redux architecture
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.5.4
  flutter_redux_dev_tools: ^0.3.0
  shared_preferences: ^0.5.4+5
  cupertino_icons: ^0.1.2
  equatable: ^0.6.1
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true